/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.client;

import edu.duke.ece651.risc.shared.MapMessage;
import javafx.stage.Stage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.testfx.api.FxAssert;
import org.testfx.api.FxRobot;
import org.testfx.framework.junit5.ApplicationExtension;
import org.testfx.framework.junit5.Start;
import org.testfx.matcher.control.TextInputControlMatchers;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(ApplicationExtension.class)
class AppTest {
//    App a;
//    @Start
//    public void start(Stage stage) throws IOException, InterruptedException {
//        a = new App();
//        a.setStageSize(stage, 100, 200, false);
//
//        MapMessage mm = new MapMessage();
//        mm.setAvailable(true);
//        a.loginShowAndWait(stage, mm);
//    }

}

