/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.server;

import edu.duke.ece651.risc.shared.Game;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws IOException, InterruptedException {
        Game g = new Game();
        String[] args = new String[3];
        args[0] = "6066";
        args[1] = "0";
        args[2] = "2";
        App.main(args);
    }
}